"""Add password_hash to User

Revision ID: 79f44d3e5bb2
Revises: 2236e27e45df
Create Date: 2025-06-27 03:07:48.929469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79f44d3e5bb2'
down_revision = '2236e27e45df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clicks', sa.Integer(), nullable=True))
        batch_op.alter_column('original_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=512),
               existing_nullable=False)
        batch_op.drop_column('date_created')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DATETIME(), nullable=True))
        batch_op.alter_column('original_url',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.drop_column('clicks')

    # ### end Alembic commands ###
